In [1]:
import numpy as np

In [4]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [5]:
np.arange(10,50,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [72]:
np.linspace(0,8,9).reshape(3,3)

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [13]:
np.random.rand(25)

array([0.897905  , 0.49535403, 0.24748686, 0.63605051, 0.71237821,
       0.03146978, 0.60354011, 0.10745222, 0.88780394, 0.54307024,
       0.35047851, 0.97247349, 0.79705791, 0.76179329, 0.376086  ,
       0.34177026, 0.84955081, 0.48106596, 0.74819071, 0.5254936 ,
       0.84703711, 0.6522361 , 0.07930751, 0.79560874, 0.3457385 ])

In [33]:
arr = np.arange(1,26)
arr1 = arr.reshape(5,5)
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [35]:
arr1[2:6,1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [37]:
arr[19]

20

In [39]:
arr.max()

25

In [40]:
arr.min()

1

In [41]:
arr.argmax()

24

In [42]:
arr.argmin()

0

In [63]:
arr2 = arr[arr>10]
arr2

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

In [65]:
arr2[arr2<=20]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [66]:
arr[arr>10][arr[arr>10]<=20]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [69]:
arr3 = arr[arr>10]
arr4 = arr3[arr3<=20]
arr4

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])